# Generated by Django 5.2.11 on 2026-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modelcustomer_city_modelcustomer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcustomer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelcustomer',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
