# Generated by Django 5.2.11 on 2026-02-11 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_modelcustomer_city_alter_modelcustomer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'api.product',
            },
        ),
    ]
