# Generated by Django 5.2.11 on 2026-02-11 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_modelproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'api.sale',
            },
        ),
    ]
